### ISSUE TITLE
Conditions and Sorting for MYSQL-Field

### ISSUE THREAD

**Issue by Acta2000** [Messa1/contao-database_select_field#1]
Is it possibile to add conditions and sorting like the old efg?

example -> Screenshot
![bedingung](https://user-images.githubusercontent.com/12759828/30795715-1cb200f4-a1cf-11e7-8d3d-18bcae94fb64.JPG)

**Comment by Messa1** [comment]
Added support in [42305ad3f7a583e4b49511bbba93326228006b05](https://github.com/Messa1/contao-database_select_field/commit/42305ad3f7a583e4b49511bbba93326228006b05)
